apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dvpwa-wdd1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dvpwa-wdd1
    app.kubernetes.io/part-of: my-vulnerable-app
  name: dvpwa-wdd1
  namespace: rh-ee-ellin-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dvpwa-wdd1
status:
  loadBalancer: {}
